#!/usr/bin/env python3
"""Table 11: Summarizer transfer (Llama / Gemini / Opus).

Omission columns are the LTT-FST controller. Llama (the main pipeline
summarizer) is read from resplit_cis_fst.json; Gemini 2.5 Pro and Claude
Opus 4 are read from fst_summarizer_resplit_cis.json (generated by
compute_fst_summarizer_transfer.py). Factuality is the unchanged 1D
scalar CRC controller.

Usage:
    python3 paper/scripts/table_11_summarizer_transfer.py
"""
import json
import numpy as np
from pathlib import Path
from care.config import PAPER_OUTPUT_DIR as OUTPUT_DIR

DATASETS = ["ACI_Bench", "MIMIC_IV_BHC"]
LABELS = {"ACI_Bench": "ACI-Bench", "MIMIC_IV_BHC": "MIMIC-BHC"}

# 95% bootstrap CI on the mean (matches Table 2 / Table 3 convention).
BOOTSTRAP_ITERS = 10000
BOOTSTRAP_SEED = 42


def bootstrap_mean_ci(values, iters=BOOTSTRAP_ITERS, seed=BOOTSTRAP_SEED):
    """95% bootstrap CI on the MEAN of the per-resplit values (already in %)."""
    rng = np.random.default_rng(seed)
    arr = np.asarray(values, dtype=float)
    n = len(arr)
    idx = rng.integers(0, n, size=(iters, n))
    means = arr[idx].mean(axis=1)
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def _summarize_per_resplit(per):
    """Means + 95% bootstrap CI on the mean for fact/omit violation, from per-resplit rows."""
    fact_viol = [r["fact_viol"] * 100 for r in per]
    omit_viol = [r["omit_viol"] * 100 for r in per]
    fact_lo, fact_hi = bootstrap_mean_ci(fact_viol)
    omit_lo, omit_hi = bootstrap_mean_ci(omit_viol)
    return {
        "fact_viol_mean": np.mean(fact_viol),
        "fact_viol_lo": fact_lo,
        "fact_viol_hi": fact_hi,
        "fact_fl": np.mean([r["fact_wl_pct"] for r in per]),
        "fact_recall": np.mean([r["fact_recall"] for r in per]) * 100,
        "omit_viol_mean": np.mean(omit_viol),
        "omit_viol_lo": omit_lo,
        "omit_viol_hi": omit_hi,
        "omit_fl": np.mean([r["omit_wl_pct"] for r in per]),
        "omit_recall": np.mean([r["omit_recall"] for r in per]) * 100,
    }


def load_llama():
    """Load Llama (main pipeline) results from the merged FST resplit CIs."""
    data = json.load(open(OUTPUT_DIR / "resplit_cis_fst.json"))
    return {ds: _summarize_per_resplit(data[ds]["per_resplit"]) for ds in DATASETS}


def _load_summarizer(summ_key):
    """Load an alternative-summarizer entry from fst_summarizer_resplit_cis.json."""
    data = json.load(open(OUTPUT_DIR / "fst_summarizer_resplit_cis.json"))
    results = {}
    for ds in DATASETS:
        entry = data.get(f"{ds}__{summ_key}")
        if entry is None:
            raise SystemExit(f"ERROR: {ds}__{summ_key} missing from "
                             f"fst_summarizer_resplit_cis.json")
        results[ds] = _summarize_per_resplit(entry["per_resplit"])
    return results


def load_gemini():
    return _load_summarizer("gemini-2.5-pro")


def load_opus():
    return _load_summarizer("claude-opus-4")


def fmt_ci(mean, lo, hi):
    return f"{mean:.1f}{{\\tiny [{lo:.1f},{hi:.1f}]}}"


def fmt_row(name, r):
    return (f"& {name} & {fmt_ci(r['fact_viol_mean'], r['fact_viol_lo'], r['fact_viol_hi'])} "
            f"& {r['fact_fl']:.1f} & {r['fact_recall']:.1f} "
            f"& {fmt_ci(r['omit_viol_mean'], r['omit_viol_lo'], r['omit_viol_hi'])} "
            f"& {r['omit_fl']:.1f} & {r['omit_recall']:.1f} \\\\")


def generate_latex(llama, gemini, opus):
    lines = []
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\caption{Summarizer transfer at $\alpha=0.15$ "
                 r"(omission controller: LTT-FST), averaged over 100 random "
                 r"70/30 resplits. Mean violation tracks $\alpha$ for all "
                 r"three summarizers across both controllers; \textsc{Care} "
                 r"adapts its operating point to each summarizer's error "
                 r"profile through recalibration. Brackets denote a 95\% "
                 r"bootstrap CI on the mean violation rate across resplits.}")
    lines.append(r"\label{tab:summarizer-transfer}")
    lines.append(r"\resizebox{\columnwidth}{!}{")
    lines.append(r"\begin{tabular}{ll ccc ccc}")
    lines.append(r"\toprule")
    lines.append(r"& & \multicolumn{3}{c}{\textbf{Hallucination}} & \multicolumn{3}{c}{\textbf{Omission}} \\")
    lines.append(r"\cmidrule(lr){3-5} \cmidrule(lr){6-8}")
    lines.append(r"Dataset & Summarizer & Viol.\% & Fl\% & Recall\% & Viol.\% & Fl\% & Recall\% \\")
    lines.append(r"\midrule")

    for ds in DATASETS:
        label = LABELS[ds]
        lines.append(f"\\multirow{{3}}{{*}}{{{label}}}")
        lines.append(fmt_row("Llama-3.3-70B", llama[ds]))
        lines.append(r"\rowcolor{gray!6}")
        lines.append(fmt_row("Gemini 2.5 Pro", gemini[ds]))
        lines.append(fmt_row("Claude Opus 4", opus[ds]))

        if ds != DATASETS[-1]:
            lines.append(r"\midrule")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


if __name__ == "__main__":
    llama = load_llama()
    gemini = load_gemini()
    opus = load_opus()

    # Print summary
    for ds in DATASETS:
        label = LABELS[ds]
        for name, r in [("Llama", llama[ds]), ("Gemini", gemini[ds]), ("Opus", opus[ds])]:
            print(f"{label} {name}: Hall viol={r['fact_viol_mean']:.1f}%, fl={r['fact_fl']:.1f}%, rec={r['fact_recall']:.1f}%  |  "
                  f"Omit viol={r['omit_viol_mean']:.1f}%, fl={r['omit_fl']:.1f}%, rec={r['omit_recall']:.1f}%")

    latex = generate_latex(llama, gemini, opus)
    out_path = OUTPUT_DIR / "table_11_summarizer_transfer.tex"
    with open(out_path, "w") as f:
        f.write(latex)
    print(f"\nSaved: {out_path}")
    print(latex)
