#!/usr/bin/env python3
"""Table: Paired Bootstrap Test — CARE (LTT-FST) vs Dev-Set Tuning at full cal size.

Complements the small-n sample-complexity table (table_crc_vs_devset.py): at full
calibration size, the n/(n+1) correction shrinks and the two methods converge on
mean violation. This table shows that on identical cal/test resplits, CARE still
has statistically significantly lower mean violation than dev-set tuning on every
non-degenerate dataset, via a paired bootstrap test.

The bootstrap pairs each resplit's (V_CARE, V_dev) and resamples with replacement.
The 95% CI and one-sided p-value are computed on the mean paired difference.

Reads paper/outputs/resplit_cis_fst.json (generated by merge_resplit_cis_fst.py);
the CARE omission controller is LTT-FST.
"""
import json
import random
from care.config import DATASETS, PAPER_OUTPUT_DIR as OUTPUT_DIR

RESPLIT_CI_PATH = OUTPUT_DIR / "resplit_cis_fst.json"
OUT_PATH = OUTPUT_DIR / "table_paired_bootstrap.tex"

ALPHA = 0.15
N_BOOT = 10_000
SEED = 42


def paired_bootstrap(diffs, n_iter=N_BOOT, seed=SEED):
    """Paired bootstrap on differences. Returns (mean, ci_lo, ci_hi, p_one_sided).

    p_one_sided tests H0: mean(diffs) <= 0 vs H1: mean(diffs) > 0 by centering
    diffs to have mean 0 and counting bootstrap resamples with mean >= observed.
    """
    rng = random.Random(seed)
    n = len(diffs)
    obs_mean = sum(diffs) / n

    means = []
    for _ in range(n_iter):
        sample = [diffs[rng.randint(0, n - 1)] for _ in range(n)]
        means.append(sum(sample) / n)
    means.sort()
    lo = means[int(0.025 * n_iter)]
    hi = means[int(0.975 * n_iter)]

    if obs_mean == 0:
        return obs_mean, lo, hi, 1.0

    shifted = [x - obs_mean for x in diffs]
    count_ge = 0
    for _ in range(n_iter):
        sample = [shifted[rng.randint(0, n - 1)] for _ in range(n)]
        if sum(sample) / n >= obs_mean:
            count_ge += 1
    p = (count_ge + 1) / (n_iter + 1)
    return obs_mean, lo, hi, p


def load_resplits():
    if not RESPLIT_CI_PATH.exists():
        raise SystemExit(f"ERROR: {RESPLIT_CI_PATH} not found. Run compute_resplit_cis.py first.")
    return json.load(open(RESPLIT_CI_PATH))


def compute_rows(data):
    rows = []
    for ds_key, meta in DATASETS.items():
        ds_data = data.get(ds_key)
        if ds_data is None or not ds_data.get("per_resplit"):
            print(f"WARNING: no resplit data for {ds_key}, skipping")
            continue

        pr = ds_data["per_resplit"]
        v_care = [r["baselines"]["fst"]["omit_viol"] for r in pr]
        v_dev = [r["baselines"]["dev_tuned"]["omit_viol"] for r in pr]

        mean_care = sum(v_care) / len(v_care) * 100
        mean_dev = sum(v_dev) / len(v_dev) * 100
        diffs_pp = [(dv - cv) * 100 for cv, dv in zip(v_care, v_dev)]

        mean_d, lo, hi, p = paired_bootstrap(diffs_pp)

        rows.append({
            "label": meta["label"],
            "mean_care": mean_care,
            "mean_dev": mean_dev,
            "delta": mean_d,
            "lo": lo,
            "hi": hi,
            "p": p,
            "n": len(pr),
        })
    return rows


def fmt_p(p):
    if p < 1e-4:
        return r"$<10^{-4}$"
    if p < 1e-3:
        return r"$<10^{-3}$"
    return f"{p:.3f}"


def generate_latex(rows):
    lines = []
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(
        r"\caption{Paired bootstrap comparison of \textsc{Care} (LTT-FST) vs "
        r"dev-set tuning at full calibration size ($\alpha = 0.15$, fractional "
        r"omission loss). For each of 100 random 70/30 cal/test resplits, "
        r"$\Delta = V_{\text{dev}} - V_{\textsc{Care}}$ is the per-resplit "
        r"violation difference in percentage points; positive values indicate "
        r"\textsc{Care} has lower violation. 95\% bootstrap CIs and one-sided "
        r"$p$-values (H$_0{:}~\mathbb{E}[\Delta] \le 0$) are computed on the "
        r"mean paired difference using 10{,}000 paired resamples. \textsc{Care} "
        r"has statistically significantly lower mean violation than dev-set "
        r"tuning on all non-degenerate datasets. The small magnitude "
        r"(0.6--3.3\,pp) reflects the $\mathcal{O}(1/n)$ asymptotic shrinkage "
        r"of the finite-sample correction at full cal size; small-$n$ behavior "
        r"is shown in Table~\ref{tab:crc-vs-devset}.}"
    )
    lines.append(r"\label{tab:paired-bootstrap}")
    lines.append(r"\begin{tabular}{l rr rcc}")
    lines.append(r"\toprule")
    lines.append(r"Dataset & \textsc{Care} V\% & Dev V\% & $\Delta$ (pp) & 95\% CI & $p$ \\")
    lines.append(r"\midrule")

    for r in rows:
        label = r["label"]
        mc = f"{r['mean_care']:.2f}"
        md = f"{r['mean_dev']:.2f}"

        if abs(r["delta"]) < 1e-6:
            delta_s = r"$0.00$"
            ci_s = "---"
            p_s = "tied"
        else:
            delta_s = f"$+{r['delta']:.2f}$"
            ci_s = f"$[+{r['lo']:.2f},\\ +{r['hi']:.2f}]$"
            p_s = fmt_p(r["p"])

        lines.append(f"{label} & {mc} & {md} & {delta_s} & {ci_s} & {p_s} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def generate_text(rows):
    out = [
        f"Paired Bootstrap: CARE (LTT-FST) vs Dev-Set Tuning (alpha={ALPHA}, 100 resplits)",
        "=" * 88,
        f"{'Dataset':<12} {'CARE V%':>9} {'Dev V%':>9} {'Delta (pp)':>12} {'95% CI':>22} {'p':>10}",
        "-" * 88,
    ]
    for r in rows:
        label = r["label"]
        if abs(r["delta"]) < 1e-6:
            out.append(f"{label:<12} {r['mean_care']:>9.2f} {r['mean_dev']:>9.2f} "
                       f"{'0.00':>12} {'---':>22} {'tied':>10}")
        else:
            ci = f"[+{r['lo']:.2f}, +{r['hi']:.2f}]"
            p_str = f"{r['p']:.4g}" if r['p'] >= 1e-4 else "<1e-4"
            out.append(f"{label:<12} {r['mean_care']:>9.2f} {r['mean_dev']:>9.2f} "
                       f"{'+' + format(r['delta'], '.2f'):>12} {ci:>22} {p_str:>10}")
    return "\n".join(out)


if __name__ == "__main__":
    data = load_resplits()
    rows = compute_rows(data)

    print(generate_text(rows))
    print()

    latex = generate_latex(rows)
    OUT_PATH.write_text(latex)
    print(f"Saved: {OUT_PATH}")
