#!/usr/bin/env python3
"""Table A1: Calibrated Thresholds.

Reads canonical LTT-FST thresholds (fst_thresholds.json, generated by
compute_fst_thresholds.py) and generates a LaTeX table of (lambda*, tau*,
gamma*) per dataset. The omission gates (tau*, gamma*) are the LTT-FST
operating point; lambda* is the unchanged 1D scalar CRC factuality threshold.
"""
import json
from care.config import DATASETS, PAPER_OUTPUT_DIR as OUTPUT_DIR

FST_THRESHOLDS_PATH = OUTPUT_DIR / "fst_thresholds.json"


def generate_table():
    fst = json.load(open(FST_THRESHOLDS_PATH))
    rows = []
    for ds_folder, ds_info in DATASETS.items():
        data = fst[ds_folder]
        lam = data["lambda"]
        tau = data["tau"]
        gamma = data["gamma"]
        rows.append((ds_info["label"], lam, tau, gamma))

    lines = []
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(
        r"\caption{Calibrated thresholds at $\alpha=0.15$. "
        r"$\lambda^*$: hallucination flagging threshold (flag if $\phat_{\mathrm{fact}} \le \lambda^*$). "
        r"$\tau^*$: importance gate (surface if $\phat_{\mathrm{imp}} \ge \tau^*$). "
        r"$\gamma^*$: non-coverage gate (surface if $1 - \phat_{\mathrm{cov}} \ge \gamma^*$).}"
    )
    lines.append(r"\label{tab:thresholds}")
    lines.append(r"\begin{tabular}{l ccc}")
    lines.append(r"\toprule")
    lines.append(r"Dataset & $\lambda^*$ & $\tau^*$ & $\gamma^*$ \\")
    lines.append(r"\midrule")

    for label, lam, tau, gamma in rows:
        lines.append(f"{label:<14} & {lam:.2f} & {tau:.2f} & {gamma:.2f} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    return "\n".join(lines)


def main():
    table = generate_table()
    out_path = OUTPUT_DIR / "table_7_thresholds.tex"
    with open(out_path, "w") as f:
        f.write(table)
    print(f"Saved: {out_path}")
    print()
    print(table)


if __name__ == "__main__":
    main()
