#!/usr/bin/env python3
"""Table A3: Judge Prompt Ablation.

Hallucination columns are read from prompt_ablation_resplit_cis.json
(generated by compute_prompt_ablation_cis.py); the omission columns are the
LTT-FST controller, read from fst_prompt_ablation.json (generated by
compute_fst_prompt_ablation.py). Both runs use the same seeds/resplits.

Format matches the paper: V% with [CI], WL%.
"""
import json
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from collections import OrderedDict
from care.config import CANONICAL_DATA_ROOT as DATA_ROOT, DATASETS, PAPER_OUTPUT_DIR as OUTPUT_DIR

ALPHA = 0.15

# 95% bootstrap CI on the mean (matches Table 2 / Table 3 convention).
BOOTSTRAP_ITERS = 10000
BOOTSTRAP_SEED = 42


def bootstrap_mean_ci(values, iters=BOOTSTRAP_ITERS, seed=BOOTSTRAP_SEED):
    rng = np.random.default_rng(seed)
    arr = np.asarray(values, dtype=float)
    n = len(arr)
    idx = rng.integers(0, n, size=(iters, n))
    means = arr[idx].mean(axis=1)
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


VARIANT_LABELS = OrderedDict([
    ("generic", "Generic"),
    ("domain", "Domain"),
])


def load_results():
    fact_path = OUTPUT_DIR / "prompt_ablation_resplit_cis.json"
    omit_path = OUTPUT_DIR / "fst_prompt_ablation.json"
    if not fact_path.exists() or not omit_path.exists():
        print(f"ERROR: need {fact_path.name} and {omit_path.name}.")
        return []

    fact_cis = json.load(open(fact_path))
    omit_cis = json.load(open(omit_path))

    rows = []
    for dataset_key, ds_meta in DATASETS.items():
        for variant_key, variant_label in VARIANT_LABELS.items():
            ci_key = f"{dataset_key}__{variant_key}"
            if ci_key not in fact_cis or ci_key not in omit_cis:
                rows.append({
                    "dataset": ds_meta["label"],
                    "prompt": variant_label,
                    "available": False,
                })
                continue

            fs = fact_cis[ci_key]["summary"]      # hallucination (unchanged)
            os_ = omit_cis[ci_key]["summary"]     # omission (LTT-FST)
            fact_per = fact_cis[ci_key]["per_resplit"]
            omit_per = omit_cis[ci_key]["per_resplit"]
            fact_ci_lo, fact_ci_hi = bootstrap_mean_ci(
                [pr["fact_viol"] * 100 for pr in fact_per])
            omit_ci_lo, omit_ci_hi = bootstrap_mean_ci(
                [pr["omit_viol"] * 100 for pr in omit_per])
            rows.append({
                "dataset": ds_meta["label"],
                "prompt": variant_label,
                "available": True,
                "fact_viol": fs["fact_viol"]["mean"] * 100,
                # 95% bootstrap CI on the mean (was: 2.5-97.5 percentile spread)
                "fact_viol_ci_lo": fact_ci_lo,
                "fact_viol_ci_hi": fact_ci_hi,
                "fact_wl_pct": fs["fact_wl_pct"]["mean"],
                "omit_viol": os_["omit_viol"]["mean"] * 100,
                "omit_viol_ci_lo": omit_ci_lo,
                "omit_viol_ci_hi": omit_ci_hi,
                "omit_wl_pct": os_["omit_wl_pct"]["mean"],
            })

    return rows


def generate_latex(rows):
    lines = []
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\caption{Prompt ablation at $\alpha=0.15$, averaged over 100 random 70/30 cal/test resplits. "
                 r"\emph{V\%}: violation rate with 95\% bootstrap CI on the mean across resplits. \emph{Fl\%}: flagged sentences (\% of total). "
                 r"CRC guarantees hold under both prompt styles across all datasets.}")
    lines.append(r"\label{tab:prompt-ablation}")
    lines.append(r"\resizebox{\columnwidth}{!}{")
    lines.append(r"\begin{tabular}{ll rr rr}")
    lines.append(r"\toprule")
    lines.append(r"& & \multicolumn{2}{c}{Hallucination} & \multicolumn{2}{c}{Omission} \\")
    lines.append(r"\cmidrule(lr){3-4} \cmidrule(lr){5-6}")
    lines.append(r"Dataset & Prompt & V\% & Fl\% & V\% & Fl\% \\")
    lines.append(r"\midrule")

    prev_ds = None
    for r in rows:
        if r["dataset"] != prev_ds:
            if prev_ds is not None:
                lines.append(r"\midrule")
            prev_ds = r["dataset"]

        ds_col = r["dataset"] if r == [x for x in rows if x["dataset"] == r["dataset"]][0] else ""

        if not r["available"]:
            lines.append(f"{ds_col} & {r['prompt']} & \\multicolumn{{4}}{{c}}{{\\textit{{not yet computed}}}} \\\\")
        else:
            fv_ci = f"{{\\tiny [{r['fact_viol_ci_lo']:.1f},{r['fact_viol_ci_hi']:.1f}]}}"
            ov_ci = f"{{\\tiny [{r['omit_viol_ci_lo']:.1f},{r['omit_viol_ci_hi']:.1f}]}}"
            lines.append(
                f"{ds_col} & {r['prompt']} & "
                f"{r['fact_viol']:.1f} {fv_ci} & {r['fact_wl_pct']:.1f} & "
                f"{r['omit_viol']:.1f} {ov_ci} & {r['omit_wl_pct']:.1f} \\\\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def generate_text(rows):
    lines = ["Prompt Ablation (α=0.15, 100 resplits)", "=" * 80]

    prev_ds = None
    for r in rows:
        if r["dataset"] != prev_ds:
            lines.append(f"\n{r['dataset']}")
            lines.append(f"  {'Prompt':20s} {'F-Viol%':>8s} {'F-WL%':>7s} | "
                        f"{'O-Viol%':>8s} {'O-WL%':>7s}")
            lines.append(f"  {'-'*55}")
            prev_ds = r["dataset"]

        if not r["available"]:
            lines.append(f"  {r['prompt']:20s}  (not yet computed)")
        else:
            fv_ci = f"[{r['fact_viol_ci_lo']:.1f},{r['fact_viol_ci_hi']:.1f}]"
            ov_ci = f"[{r['omit_viol_ci_lo']:.1f},{r['omit_viol_ci_hi']:.1f}]"
            lines.append(
                f"  {r['prompt']:20s} {r['fact_viol']:5.1f} {fv_ci:>10s} {r['fact_wl_pct']:7.1f} | "
                f"{r['omit_viol']:5.1f} {ov_ci:>10s} {r['omit_wl_pct']:7.1f}"
            )

    return "\n".join(lines)


if __name__ == "__main__":
    rows = load_results()

    if not rows:
        print("No data available. Run compute_prompt_ablation_cis.py first.")
        raise SystemExit(1)

    print(generate_text(rows))
    print()

    latex = generate_latex(rows)
    out_path = OUTPUT_DIR / "table_8_prompt_ablation.tex"
    out_path.write_text(latex)
    print(f"Saved: {out_path}")
