#!/usr/bin/env python3
"""
Table A4: Binary vs. Fractional Omission Loss Comparison

Shows that while all CRC methods hold under fractional loss (mean fraction
of omissions missed per doc <= alpha), binary loss (probability that ANY
omission is missed in a given doc) can be much higher, especially on
high-compression datasets like BHC and PubMed.

All point estimates are resplit means from 100 random 70/30 cal/test splits.

Requires: resplit_cis_fst.json (generated by merge_resplit_cis_fst.py).
"""
import json
import numpy as np
from pathlib import Path
from care.config import DATASETS, PAPER_OUTPUT_DIR as OUTPUT_DIR

RESPLIT_CI_PATH = OUTPUT_DIR / "resplit_cis_fst.json"
ALPHA = 0.15

# Maps internal key → display name. LTT-FST is the CARE omission controller
# (headline, bold).
METHOD_MAP = [
    ("fst",          "LTT-FST"),
    ("1d_imp",       "1D-Importance"),
    ("product",      "Product"),
    ("union_bound",  "Union Bound"),
]


def load_results():
    if not RESPLIT_CI_PATH.exists():
        print(f"ERROR: {RESPLIT_CI_PATH} not found. Run compute_resplit_cis.py first.")
        return []

    resplit_cis = json.load(open(RESPLIT_CI_PATH))

    rows = []
    for ds_folder, ds_info in DATASETS.items():
        rs = resplit_cis.get(ds_folder)
        if rs is None or len(rs.get("per_resplit", [])) == 0:
            print(f"WARNING: {ds_folder} has no resplit data, skipping")
            continue

        bs = rs.get("baselines_summary", {})
        if not bs:
            print(f"WARNING: {ds_folder} has no baselines_summary, skipping")
            continue

        for key, name in METHOD_MAP:
            if key not in bs:
                continue
            m = bs[key]
            frac = m["omit_viol"]["mean"]
            binary = m["omit_binary_viol"]["mean"]

            rows.append({
                "dataset": ds_info["label"],
                "method": name,
                "frac": frac,
                "binary": binary,
                "frac_holds": frac <= ALPHA,
                "binary_holds": binary <= ALPHA,
            })

    return rows


def generate_table(rows):
    latex = []
    latex.append(r"\begin{table}[t]")
    latex.append(r"\centering")
    latex.append(r"\small")
    latex.append(r"\caption{Fractional vs.\ binary omission loss at $\alpha=0.15$. "
                 r"Point estimates are means over 100 random cal/test resplits. "
                 r"Fractional loss measures the mean fraction of true omissions missed per document; "
                 r"binary loss measures the fraction of documents with \emph{any} missed omission. "
                 r"All CRC methods achieve valid fractional coverage. "
                 r"Binary loss is substantially higher on high-compression datasets (BHC, PubMed), "
                 r"where documents have many true omissions.}")
    latex.append(r"\label{tab:binary-vs-fractional}")
    latex.append(r"\begin{tabular}{ll cc}")
    latex.append(r"\toprule")
    latex.append(r"Dataset & Method & Frac.\% & Binary\% \\")
    latex.append(r"\midrule")

    prev_dataset = None
    for row in rows:
        ds = row["dataset"]
        if prev_dataset and ds != prev_dataset:
            latex.append(r"\midrule")

        frac_str = f"{row['frac']*100:.1f}"
        binary_str = f"{row['binary']*100:.1f}"

        if not row["frac_holds"]:
            frac_str += r"$^\dagger$"
        if not row["binary_holds"]:
            binary_str += r"$^\dagger$"

        method = row["method"]
        if method == "LTT-FST":
            method = r"\textbf{LTT-FST}"
            frac_str = r"\textbf{" + frac_str + r"}"

        ds_cell = ds if ds != prev_dataset else ""
        latex.append(f"  {ds_cell} & {method} & {frac_str} & {binary_str} \\\\")
        prev_dataset = ds

    latex.append(r"\bottomrule")
    latex.append(r"\end{tabular}")
    latex.append(r"\vspace{2pt}")
    latex.append(r"\par\small $^\dagger$Exceeds $\alpha=0.15$.")
    latex.append(r"\end{table}")

    return "\n".join(latex)


def main():
    rows = load_results()
    if not rows:
        print("No data available.")
        return

    table = generate_table(rows)

    # Save LaTeX
    out_path = OUTPUT_DIR / "table_5_binary_vs_fractional.tex"
    with open(out_path, "w") as f:
        f.write(table)
    print(f"Saved to {out_path}")

    # Print summary
    print("\n" + "=" * 70)
    print("Binary vs Fractional Omission Loss Summary (100 resplits)")
    print("=" * 70)
    print(f"{'Dataset':<12} {'Method':<15} {'Frac%':>7} {'Binary%':>8}  {'Gap':>6}")
    print("-" * 70)
    prev_ds = None
    for row in rows:
        if prev_ds and row["dataset"] != prev_ds:
            print()
        gap = row["binary"] - row["frac"]
        marker = " ***" if gap > 0.3 else ""
        print(f"{row['dataset']:<12} {row['method']:<15} {row['frac']*100:>6.1f}% {row['binary']*100:>7.1f}%  {gap*100:>+5.1f}%{marker}")
        prev_ds = row["dataset"]

    print()
    print(table)


if __name__ == "__main__":
    main()
