#!/usr/bin/env python3
"""Table 3: Baseline Comparison (Omission Controller).

Compares LTT-FST (the CARE omission controller) vs alternative methods:
- 1D-Importance (threshold on importance only, no coverage gate)
- Product (single threshold on τ×(1-γ))
- Union Bound (Bonferroni split of α across τ and γ)
- Max-F1 (pick (τ,γ) that maximizes F1 on cal — no risk constraint)
- Fixed-threshold (τ=γ=0.5 on LLM-judge signal; label-free empirical baseline)

All methods use fractional loss. Shows violation%, workload, recall.
All point estimates are resplit means from 100 random 70/30 cal/test splits.

Requires: resplit_cis_fst.json (generated by merge_resplit_cis_fst.py).
"""
import json
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from care.config import DATASETS, PAPER_OUTPUT_DIR as OUTPUT_DIR

RESPLIT_CI_PATH = OUTPUT_DIR / "resplit_cis_fst.json"

ALPHA = 0.15
BOOTSTRAP_ITERS = 10000
BOOTSTRAP_SEED = 42

# Rigorously-guaranteed methods (finite-sample CRC, compete for bold).
# LTT-FST is the CARE omission controller and the headline method.
GUARANTEED = [
    ("fst",          "LTT-FST"),
    ("1d_imp",       "1D-Imp"),
    ("product",      "Product"),
    ("union_bound",  "Union Bnd"),
]

# Methods without finite-sample guarantees (shown for comparison, never bolded)
UNGUARANTEED = [
    ("max_f1",          "Max-F1",    r"*"),    # oracle F1-optimal on cal, ignores alpha
    ("fixed_threshold", "Fixed-0.5", r"*"),    # label-free; no calibration, no alpha
]

METHOD_MAP = ([(k, n) for k, n in GUARANTEED]
              + [(k, n) for k, n, _ in UNGUARANTEED])


def bootstrap_mean_ci(values, iters=BOOTSTRAP_ITERS, seed=BOOTSTRAP_SEED):
    rng = np.random.default_rng(seed)
    n = len(values)
    arr = np.asarray(values)
    idx = rng.integers(0, n, size=(iters, n))
    means = arr[idx].mean(axis=1)
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def load_results():
    if not RESPLIT_CI_PATH.exists():
        print(f"ERROR: {RESPLIT_CI_PATH} not found. Run compute_resplit_cis.py first.")
        return {}

    resplit_cis = json.load(open(RESPLIT_CI_PATH))

    all_data = {}
    for dataset, meta in DATASETS.items():
        rs = resplit_cis.get(dataset)
        if rs is None or len(rs.get("per_resplit", [])) == 0:
            print(f"WARNING: {dataset} has no resplit data, skipping")
            continue

        bs = rs.get("baselines_summary", {})
        if not bs:
            print(f"WARNING: {dataset} has no baselines_summary, skipping")
            continue

        per_resplit = rs["per_resplit"]

        methods = {}
        for key, name in METHOD_MAP:
            if key not in bs:
                continue
            m = bs[key]
            per_viol = [pr["baselines"][key]["omit_viol"] * 100 for pr in per_resplit
                        if key in pr.get("baselines", {})]
            ci_lo, ci_hi = bootstrap_mean_ci(per_viol)
            methods[name] = {
                "viol": m["omit_viol"]["mean"] * 100,
                "viol_ci_lo": ci_lo,
                "viol_ci_hi": ci_hi,
                "wl": m["omit_wl"]["mean"],
                "wl_pct": m["omit_wl_pct"]["mean"],
                "recall": m["omit_recall"]["mean"] * 100,
            }

        all_data[meta["label"]] = methods

    return all_data


def _row_color_open(idx):
    """Alternating gray for odd-indexed rows within a dataset block."""
    return r"\rowcolor{gray!6}" if idx % 2 == 1 else ""


def _fmt_viol(m):
    return f"{m['viol']:.1f} [{m['viol_ci_lo']:.1f}, {m['viol_ci_hi']:.1f}]"


def _is_significant_violation(m):
    """True iff 95% bootstrap CI on the mean V% lies entirely above alpha."""
    return m["viol_ci_lo"] > ALPHA * 100


def generate_latex(all_data):
    lines = []
    lines.append(r"\begin{table}[t!]")
    lines.append(r"\centering")
    lines.append(r"\footnotesize")
    lines.append(r"\caption{Omission controller comparison at $\alpha=0.15$ (fractional loss), "
                 r"averaged over 100 random 70/30 cal/test resplits. "
                 r"V\% is reported as mean with 95\% bootstrap CI over resplits. "
                 r"\textbf{Above the dashed line}: methods with finite-sample CRC guarantees; "
                 r"\textsc{LTT-FST} is the \textsc{Care} omission controller. "
                 r"Bold marks fewest flagged sentences among those whose CI lower bound "
                 r"does not exceed $\alpha$. "
                 r"\textbf{Below the dashed line}: empirical thresholding baselines with no "
                 r"finite-sample guarantee: Max-F1 (oracle F1-optimal $(\tau,\gamma)$ on cal "
                 r"using labels, ignores $\alpha$) and Fixed-0.5 (label-free: "
                 r"$\tau{=}\gamma{=}0.5$, no calibration). Red V\% marks cells whose CI "
                 r"lies entirely above $\alpha$ (empirically significant violation).}")
    lines.append(r"\label{tab:baselines}")
    lines.append(r"\resizebox{\columnwidth}{!}{")
    lines.append(r"\begin{tabular}{ll rrr}")
    lines.append(r"\toprule")
    lines.append(r"Dataset & Method & V\% [95\% CI] & Flagged & Rec\% \\")
    lines.append(r"\midrule")

    for ds_idx, (ds_label, methods) in enumerate(all_data.items()):
        if ds_idx > 0:
            lines.append(r"\midrule")

        # Bold rule: lowest Flagged among guaranteed methods whose CI
        # lower bound is at or below alpha (consistent with the guarantee).
        guar_present = [(k, n) for k, n in GUARANTEED if n in methods]
        guar_valid = [(k, n) for k, n in guar_present
                      if not _is_significant_violation(methods[n])]
        if guar_valid:
            wl_winner_name = min(guar_valid, key=lambda kn: methods[kn[1]]["wl"])[1]
        else:
            wl_winner_name = None

        row_idx = 0
        # Guaranteed methods
        for _, name in GUARANTEED:
            if name not in methods:
                continue
            m = methods[name]
            rc = _row_color_open(row_idx)
            if rc:
                lines.append(rc)

            is_winner = (name == wl_winner_name)
            v_str = _fmt_viol(m)
            wl_str = f"{m['wl']:.1f} ({m['wl_pct']:.1f}\\%)"
            rec_str = f"{m['recall']:.1f}"

            if is_winner:
                method_cell = rf"\textbf{{{name}}}"
                v_cell = rf"\textbf{{{v_str}}}"
                wl_cell = rf"\textbf{{{m['wl']:.1f}}} ({m['wl_pct']:.1f}\%)"
            else:
                method_cell = name
                v_cell = v_str
                wl_cell = wl_str

            ds_cell = ds_label if row_idx == 0 else ""
            lines.append(f"{ds_cell} & {method_cell} & {v_cell} & {wl_cell} & {rec_str} \\\\")
            row_idx += 1

        lines.append(r"\cdashline{2-5}")

        # Unguaranteed methods (grayed; red V% if CI lower bound > alpha)
        for _, name, mark in UNGUARANTEED:
            if name not in methods:
                continue
            m = methods[name]
            rc = _row_color_open(row_idx)
            if rc:
                lines.append(rc)

            v_color = "redflag" if _is_significant_violation(m) else "gray"

            method_cell = rf"\textcolor{{gray}}{{{name}\textsuperscript{{{mark}}}}}"
            v_cell = rf"\textcolor{{{v_color}}}{{{_fmt_viol(m)}}}"
            wl_cell = rf"\textcolor{{gray}}{{{m['wl']:.1f} ({m['wl_pct']:.1f}\%)}}"
            rec_cell = rf"\textcolor{{gray}}{{{m['recall']:.1f}}}"

            lines.append(f" & {method_cell} & {v_cell} & {wl_cell} & {rec_cell} \\\\")
            row_idx += 1

    lines.append(r"\bottomrule")
    lines.append(r"\multicolumn{5}{l}{\textsuperscript{*}No finite-sample guarantee; empirical numbers shown for comparison.} \\")
    lines.append(r"\end{tabular}}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


def generate_text(all_data):
    method_order = [name for _, name in METHOD_MAP]

    lines = ["Baseline Comparison — Omission Controller (α=0.15, fractional loss, 100 resplits)", "=" * 80]

    for ds_label, methods in all_data.items():
        lines.append(f"\n{ds_label}")
        lines.append(f"  {'Method':15s} {'Viol%':>8s} {'CI95':>14s} {'WL':>8s} {'WL%':>8s} {'Recall%':>8s}")
        lines.append(f"  {'-'*70}")
        for method in method_order:
            if method not in methods:
                continue
            m = methods[method]
            marker = " (CARE)" if method == "LTT-FST" else ""
            ci = f"[{m['viol_ci_lo']:.1f},{m['viol_ci_hi']:.1f}]"
            lines.append(
                f"  {method:15s} {m['viol']:8.1f} {ci:>14s} {m['wl']:8.1f} {m['wl_pct']:7.1f}% {m['recall']:8.1f}{marker}"
            )

    return "\n".join(lines)


def render_table_png(all_data, out_path):
    """Render the baselines comparison table as a clean PNG image."""
    method_order = [name for _, name in METHOD_MAP]
    headers = ["Dataset", "Method", "Viol% [95% CI]", "Flagged", "Recall%"]

    cell_data = []
    for ds_label, methods in all_data.items():
        first = True
        for method in method_order:
            if method not in methods:
                continue
            m = methods[method]
            cell_data.append([
                ds_label if first else "",
                method,
                f"{m['viol']:.1f} [{m['viol_ci_lo']:.1f}, {m['viol_ci_hi']:.1f}]",
                f"{m['wl']:.1f} ({m['wl_pct']:.1f}%)",
                f"{m['recall']:.1f}",
            ])
            first = False

    fig, ax = plt.subplots(figsize=(10, 0.6 + 0.35 * len(cell_data)))
    ax.axis("off")
    ax.set_title("Table 3: Omission Controller Baselines (\u03b1=0.15, fractional loss)",
                 fontsize=13, fontweight="bold", pad=12)

    table = ax.table(
        cellText=cell_data,
        colLabels=headers,
        cellLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1.0, 1.5)

    for j in range(len(headers)):
        cell = table[0, j]
        cell.set_facecolor("#4472C4")
        cell.set_text_props(color="white", fontweight="bold")

    ds_group = 0
    for i, row_data in enumerate(cell_data):
        if row_data[0]:
            if i > 0:
                ds_group += 1
        is_headline = row_data[1] == "LTT-FST"
        for j in range(len(headers)):
            cell = table[i + 1, j]
            if is_headline:
                cell.set_facecolor("#E2EFDA")
                cell.set_text_props(fontweight="bold")
            elif ds_group % 2 == 0:
                cell.set_facecolor("#D9E2F3")
            else:
                cell.set_facecolor("#FFFFFF")

    fig.savefig(out_path, bbox_inches="tight", dpi=200, facecolor="white")
    plt.close(fig)


if __name__ == "__main__":
    all_data = load_results()

    print(generate_text(all_data))
    print()

    latex = generate_latex(all_data)
    out_path = OUTPUT_DIR / "table_3_baselines.tex"
    out_path.write_text(latex)
    print(f"Saved: {out_path}")

