#!/usr/bin/env python3
"""
Table 15: Tail-Risk Diagnostics for the Omission Controller

Reports empirical percentiles (P50, P75, P90, P95, P99) of the per-document
fractional omission loss, pooled across all 100 cal/test resplits and all
test documents within each resplit. Complements the marginal-mean view in
Tables 2 and 3 by surfacing the per-instance distribution that the CRC
guarantee does not directly bound.

Requires: tail_risk_cis.json (generated by compute_tail_risk.py).
"""
import json
from pathlib import Path

from care.config import DATASETS, PAPER_OUTPUT_DIR as OUTPUT_DIR

TAIL_PATH = OUTPUT_DIR / "tail_risk_cis.json"
ALPHA = 0.15


def load_results():
    if not TAIL_PATH.exists():
        print(f"ERROR: {TAIL_PATH} not found. Run compute_tail_risk.py first.")
        return []

    data = json.load(open(TAIL_PATH))
    rows = []
    for ds_folder in DATASETS:
        rec = data.get(ds_folder)
        if rec is None:
            print(f"WARNING: {ds_folder} not in tail_risk_cis.json, skipping")
            continue
        po = rec["pooled_summary"]["omit_fractional"]
        rows.append({
            "dataset": DATASETS[ds_folder]["label"],
            "n_docs": int(po["n_docs"]),
            "mean": po["mean"],
            "P50": po["P50"],
            "P75": po["P75"],
            "P90": po["P90"],
            "P95": po["P95"],
            "P99": po["P99"],
            "max": po["max"],
        })
    return rows


def generate_table(rows):
    latex = []
    latex.append(r"\begin{table}[h]")
    latex.append(r"\centering")
    latex.append(r"\small")
    latex.append(r"\caption{Tail-risk diagnostics for the omission controller at "
                 r"$\alpha = 0.15$. Reports empirical percentiles of the per-document "
                 r"fractional omission loss, pooled across all 100 cal/test resplits "
                 r"and all test documents within each resplit (\emph{$n$} pooled "
                 r"observations). The mean is at or below $\alpha$ on every dataset, "
                 r"empirically validating CRC. The tail behavior splits by document "
                 r"structure: long-document datasets with many true omissions per "
                 r"document (BHC, Priv-DS, SumPubMed) show smooth tails with $P95$ "
                 r"of 0.25--0.40; short-document datasets with 1--2 true omissions "
                 r"per document (ACI-Bench, MIMIC-CXR) show bimodal tails because "
                 r"the fractional loss can only take a few discrete values---missing "
                 r"a single omission in a document with one true omission yields "
                 r"$L = 1$.}")
    latex.append(r"\label{tab:tail-risk}")
    latex.append(r"\begin{tabular}{l r r r r r r r}")
    latex.append(r"\toprule")
    latex.append(r"Dataset & $n$ & Mean & $P50$ & $P75$ & $P90$ & $P95$ & $P99$ \\")
    latex.append(r"\midrule")

    for row in rows:
        latex.append(
            f"  {row['dataset']} & {row['n_docs']:,} & "
            f"{row['mean']:.3f} & {row['P50']:.3f} & {row['P75']:.3f} & "
            f"{row['P90']:.3f} & {row['P95']:.3f} & {row['P99']:.3f} \\\\"
        )

    latex.append(r"\bottomrule")
    latex.append(r"\end{tabular}")
    latex.append(r"\end{table}")

    return "\n".join(latex)


def main():
    rows = load_results()
    if not rows:
        print("No data available.")
        return

    table = generate_table(rows)
    out_path = OUTPUT_DIR / "table_15_tail_risk.tex"
    with open(out_path, "w") as f:
        f.write(table)
    print(f"Saved to {out_path}")

    print("\n" + "=" * 90)
    print(f"Tail-risk per-document fractional loss (alpha={ALPHA}, pooled across 100 resplits)")
    print("=" * 90)
    print(f"  {'Dataset':12s} | {'n':>7s} | {'Mean':>6s} {'P50':>6s} {'P75':>6s} {'P90':>6s} {'P95':>6s} {'P99':>6s}")
    print("  " + "-" * 86)
    for r in rows:
        print(f"  {r['dataset']:12s} | {r['n_docs']:>7,} | "
              f"{r['mean']:>6.3f} {r['P50']:>6.3f} {r['P75']:>6.3f} "
              f"{r['P90']:>6.3f} {r['P95']:>6.3f} {r['P99']:>6.3f}")
    print()
    print(table)


if __name__ == "__main__":
    main()
